name: PySpark CI Pipeline

# Se ejecuta cada vez que subas código a la rama principal
on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  test-y-calidad:
    runs-on: ubuntu-latest

    steps:
    - name: Descargar el repositorio
      uses: actions/checkout@v4

    # Spark necesita Java por debajo para funcionar
    - name: Configurar Java 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # Configuramos Python
    - name: Configurar Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    # Instalamos las librerías que te dieron guerra en local
    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install pytest python-dotenv loguru typer tqdm
        pip install -e .

    # Ejecutamos el test
    - name: Ejecutar Pytest
      run: |
        pytest tests/